### ISSUE TITLE
Improve Security: Store Secrets in a Mounted File Instead of Environment Variables

### ISSUE THREAD

**Issue by gitwildnow** [Reaper0x1/bitwarden-portal#8]
Currently, vault credentials (passwords, client secrets, and API keys) are stored in environment variables inside the container. This presents a security risk because:

- Environment variables can be accessed by any process inside the container.
- Secrets are exposed to anyone with docker inspect or docker exec env access.
- Sensitive values may unintentionally appear in logs or crash reports.

### Proposed Solution

Instead of environment variables, credentials could be stored in a file that is mounted inside the container at runtime.

### Steps to Implement
1. Store secrets in a .secrets file on the host machine:
Create a secrets.env file with the necessary credentials:

```
BW_SOURCE_ACCOUNT=source@mail.com
BW_SOURCE_PASSWORD=source-password
BW_SOURCE_CLIENT_ID=user.xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
BW_SOURCE_CLIENT_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
BW_DEST_ACCOUNT=dest@mail.com
BW_DEST_PASSWORD=dest-password
BW_DEST_CLIENT_ID=user.xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
BW_DEST_CLIENT_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

```
2. Modify docker-compose.yml to mount the secrets file (read-only):
```
services:
  bitwarden-portal:
    build: .
    volumes:
      - ./secrets.env:/run/secrets/secrets.env:ro  # Read-only mount
```
3. Modify backup.sh to read secrets from the file instead of using env vars:
Replace:
`export BW_SOURCE_PASSWORD="$BW_SOURCE_PASSWORD"
`
With:
```
set -o allexport
source /run/secrets/secrets.env
set +o allexport
```
4. Unset variables after use to reduce exposure:
`unset BW_SOURCE_PASSWORD BW_DEST_PASSWORD
`
### Benefits of This Approach:
✔️ Prevents secrets from being exposed in docker inspect or process lists
✔️ Restricts access via read-only volume mount
✔️ Reduces the risk of secrets leaking into logs
✔️ Works without requiring major architectural changes

**Comment by Reaper0x1** [comment]
Good to know! I will look into in the next days

**Comment by randyprice** [comment]
@gitwildnow Why use a secrets.env file as a standard bind mount instead of creating a [Docker secret](https://docs.docker.com/engine/swarm/secrets/) for each piece of sensitive data?

An implementation of this could be allowing `*_FILE` versions of variables containing sensitive data to be used in place of the non-`*_FILE` variables. For example, the environment variable `BW_SOURCE_PASSWORD_FILE` points to the Docker secret mounted into the container, and its contents are that of what `BW_SOURCE_PASSWORD` would be.

```
services:
  bitwarden-portal:
    ...
    secrets:
      - bw-source-password # mounted to `/run/secrets/bw-source-password by default`

secrets:
  bw-source-password:
    # If Docker is to create the secret at runtime:
    file: ./path/to/password/file
    # Or, if the secret is created via `docker secret create`:
    external: true
```
